name: dev-release
on:
  push:
    branches:
      - dev
  
  # allow manual dispatch on action tab
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  aws-cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - run: npm install --include dev
            
      - name: Configure Env Vars
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env.dev'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::372513869951:role/PowerUserAccessForGithubActions # IAM role for encrypt_dev account
          role-session-name: PowerUserAccessForGithubActionsSession

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_stack: 'miro-beta/*'
          actions_comment: true

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_stack: 'miro-beta/*'
          # cdk_version: '2.139.0'

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'miro-beta/*'
          cdk_args: '--require-approval never'
          actions_comment: false
