name: prd-release
on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  check-current-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        # 1. Get the list of branches ref where this tag exists
        # 2. Remove 'origin/' from that result
        # 3. Put that string in output
        # => We can now use function 'contains(list, item)''
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."
          
  aws-cdk-deploy:
    runs-on: ubuntu-latest
    # Wait for check step to finish
    needs: check-current-branch
    # only run if tag is present on branch 'main'
    if: contains(${{ needs.check.outputs.branch }}, 'main')`
    steps:
      - uses: actions/setup-node@v4
      
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-main-
            
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - run: npm install --include dev
            
      - name: Configure Env Vars
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env.prd'
      
      - name: Override STAGE for Production Release
        run: echo "STAGE=prod" >> $GITHUB_ENV
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::381491983184:role/LimitedUserAccessForGithubActions # IAM role for encrypt_prd account
          role-session-name: LimitedUserAccessForGithubActionsSession

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_stack: 'miro-prod/*'
          actions_comment: true

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_stack: 'miro-prod/*'
          # cdk_version: '2.139.0'

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'miro-prod/*'
          cdk_args: '--require-approval never'
          actions_comment: false
